### ISSUE TITLE
Has conflicts with Vetur

### ISSUE THREAD

**Issue by HelloDeadline** [hollowtree/vscode-vue-snippets#13]
If I install both this plugin and Vetur, snippets won't work within `<template>`. 
After I disabled Vetur, I could use, for example `slotE` within `<template>`.

**Comment by hollowtree** [comment]
Maybe you can try add these into settings.
```
"files.associations": {
"*.vue": "html"
}
```

**Comment by HelloDeadline** [comment]
Yes, it helps, but I want to have nice Intellisence and syntax highlight which is much better without this setting. 
I created my own snippets for slots. They work in vue as vue, not vue as html. (User Snippets => Vue Language). 
Maybe you would like to expand this set for Vue language as well.

**Comment by hollowtree** [comment]
Try update extension and remove files.associations in setting, has it worked as you expected?
