### ISSUE TITLE
为啥beforeRouteLeave钩子函数snippet会使用箭头函数？

### ISSUE THREAD

**Issue by Kuohao-wu** [hollowtree/vscode-vue-snippets#15]
beforeRouteLeave钩子函数使用箭头函数，该函数作用域的this就不能正确指向vue实例，不明白为啥会这样做，但是希望知道，如何修改插件默认的snippet？

**Comment by hollowtree** [comment]
抱歉，回复迟了，刚刚才看到，稍后会修复相关 snippets。自定义 snippets 可以看下这个： [https://code.visualstudio.com/docs/editor/userdefinedsnippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets)
