### ISSUE TITLE
请问如何修改部分代码段？

### ISSUE THREAD

**Issue by snoopy83101** [hollowtree/vscode-vue-snippets#18]
比如我写else的时候就想第一个要if后面的else,不想要vue-snippets中的代码段。
或者我想稍微更改几个代码段如何来做呢？

**Comment by hollowtree** [comment]
@snoopy83101 你可以自定义snippets，具体的参考这里(Creating your own snippets)[https://code.visualstudio.com/docs/editor/userdefinedsnippets]。另外windows系统安装的extensions目录大都在这里：`C:\Users\{username}\.vscode\extensions`，你可以试下改这里面的，不过感觉应该还是自定义更好点。如果你想用以前版本的vue-snippets，vscode的extensions列表的每项右下角都有个设置图标，点那里可以选择用以前的版本。还有，能具体说下你想修改的是哪个snippet（`vElse`那个么）以及期望的代码段吗？

**Comment by hollowtree** [comment]
可以截个图么？就是你写else之后点tab之前的提示列表的截图

**Comment by snoopy83101** [comment]
![wx20181220-134732](https://user-images.githubusercontent.com/24613784/50266231-da277780-045d-11e9-8f6a-b6db1165272d.png)
![wx20181220-134715](https://user-images.githubusercontent.com/24613784/50266237-de539500-045d-11e9-85c7-f820faeedc1f.png)
