### ISSUE TITLE
Unable to get html completion at first

### ISSUE THREAD

**Issue by ZiFFeL1992** [hollowtree/vscode-vue-snippets#19]
If I have for example:

```
<div class></div>
```

and press `crtl` + `space` to display hints, I see

![image](https://user-images.githubusercontent.com/5492960/50407904-0a19a680-07e1-11e9-9c97-10ada605bb74.png)

But I should be able to see HTML suggestions, I can do it by deleting the last `s` and pressing `crtl` + `space` again:

![image](https://user-images.githubusercontent.com/5492960/50407906-261d4800-07e1-11e9-9a40-7d3d0e6cab36.png)

Of course I have full html completion if I disable the extension but I actually love it :)

**Comment by hollowtree** [comment]
I can't reproduce what you described. I just type `class`, without pressing `crtl` + `space`,  `class` always appears at the top.
![gif](https://user-images.githubusercontent.com/17763391/50418129-dda76e00-0864-11e9-83e0-bae9cc87bfa2.gif)

Could you list your settings and the extensions you have installed?

**Comment by ZiFFeL1992** [comment]
Sure:

```
Zignd.html-css-class-completion
albymor.increment-selection
cdsama.shell-snippets
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
cssho.vscode-svgviewer
dakshmiglani.hex-to-rgba
dbaeumer.vscode-eslint
EditorConfig.EditorConfig
eg2.tslint
eg2.vscode-npm-script
eriklynd.json-tools
esbenp.prettier-vscode
felipecaputo.git-project-manager
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
formulahendry.code-runner
freakypie.code-python-isort
glen-84.sass-lint
hollowtree.vue-snippets
HookyQR.beautify
JakeWilson.vscode-placeholder-images
jolaleye.horizon-theme-vscode
magicstack.MagicPython
maximerouiller.slugify-vscode
mikestead.dotenv
mrmlnc.vscode-attrs-sorter
mrmlnc.vscode-scss
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.python
ms-vscode.Go
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
mubaidr.vuejs-extension-pack
octref.vetur
patbenatar.advanced-new-file
PeterJausovec.vscode-docker
PKief.material-icon-theme
redhat.vscode-yaml
robinbentley.sass-indented
sasa.vscode-sass-format
Shan.code-settings-sync
shanoor.vscode-nginx
shardulm94.trailing-spaces
shinnn.stylelint
sleistner.vscode-fileutils
teabyii.ayu
tombonnike.vscode-status-bar-format-toggle
VisualStudioExptTeam.vscodeintellicode
vscoss.vscode-ansible
wayou.vscode-todo-highlight
wholroyd.jinja
wix.vscode-import-cost
xabikos.JavaScriptSnippets
yzhang.markdown-all-in-one
zamerick.vscode-caddyfile-syntax
zhuangtongfa.Material-theme
```

Seems like enabling https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion breaks it, I don't know what could cause it, let me know if I can help :)

**Comment by ZiFFeL1992** [comment]
Also:
![image](https://user-images.githubusercontent.com/5492960/50446920-e2792a00-0917-11e9-90dd-cb02ddc3d09c.png)

I think it shouldn't display those snippets..

**Comment by hollowtree** [comment]
Seems like this question caused by `Zignd.html-css-class-completion`, it reappears if i only enable  `Zignd.html-css-class-completion` and disable other extensions then edit `.html` file, maybe you can try it.
