### ISSUE TITLE
simple but annoying: nuxt-link have an extra "/"

### ISSUE THREAD

**Issue by Muhammad-Yasser1** [hollowtree/vscode-vue-snippets#21]
when you load nuxt link from the abbreviation it loads with a "/" in the opening tag:
```
<nuxt-link to=""/></nuxt-link>
```

and will be nicer if it loads "to" attribute with a v-bind abbreviation ":"

awesome plugin BTW 👍

**Comment by hollowtree** [comment]
Thanks for your feedback, I had remove `/` and add `:to` as a option just now,
