### ISSUE TITLE
Data with arrow function

### ISSUE THREAD

**Issue by oiagorodrigues** [hollowtree/vscode-vue-snippets#22]
Hi,

can you add something like this, please? 
I prefer this syntax than the other data one and it's anoying to have to write that all the time.

    data: () => ({
        
    })

I tried to do something like this, but I don't know how to make this thing work on the actual extension.

    "dataWithArrow": {
        "prefix": "dataWithArrow",
        "body": [
            "data: () => ({",
            "\t\t$1",
            "}),$0"
        ],
        "description": "The data object for the Vue instance with arrow function."
    }

**Comment by hollowtree** [comment]
Hi, you can set this snippet in your own local sinppets, you can select   `File > Preferences > User Snippets`,  choose the language (javascript), save this snippet to `javascript.json`, then this snippet should work. The [Creating snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets) topic contains all information for creating snippets.
