### ISSUE TITLE
Syntax typo fix

### ISSUE THREAD

**Issue by syedsimanta03** [hollowtree/vscode-vue-snippets#24]
newVueRouter | const router = newVueRouter({ })
-- | --
Not :-1: 
const router = new **VueRouter**({
 
})

Itz :+1: 
const router = new **Router**({

})

**Comment by hcgaron** [comment]
@syedsimanta03 has this been fixed?  Should I open a PR?

**Comment by hollowtree** [comment]
In [Vue Router Docs](https://router.vuejs.org/guide/#javascript), it's:
```js
// 3. Create the router instance and pass the `routes` option
// You can pass in additional options here, but let's
// keep it simple for now.
const router = new VueRouter({
    routes // short for `routes: routes`
})
```
I've add a snippet `importVueRouter`, its body is `import VueRouter from 'vue-router'`
