### ISSUE TITLE
注释功能异常:

### ISSUE THREAD

**Issue by PLQin** [hollowtree/vscode-vue-snippets#26]
注释功能异常: 

![image](https://user-images.githubusercontent.com/41833007/56717940-5e716a80-6770-11e9-8f8e-89a565841f32.png)

使用快捷键  - `ctrl + /` ,  出现异常的注释, 

建议屏蔽 html 中的注释, 使用 vscode 本身的注释功能

_Originally posted by @plqin-xiaohao in https://github.com/hollowtree/vscode-vue-snippets/issues/3#issuecomment-486555666_

**Comment by Sean-Zheng** [comment]
怎么屏蔽html中的注释？

**Comment by whoopsHzh** [comment]
> 注释功能异常：
> 
> ![图片](https://user-images.githubusercontent.com/41833007/56717940-5e716a80-6770-11e9-8f8e-89a565841f32.png)
> 
> 使用快捷键 - `ctrl + /`，出现异常的注释，
> 
> 建议屏蔽html中的注释，使用vscode本身的注释功能
> 
> _最初由@ plqin-xiaohao [发表](https://github.com/hollowtree/vscode-vue-snippets/issues/3#issuecomment-486555666)于[＃3（评论）](https://github.com/hollowtree/vscode-vue-snippets/issues/3#issuecomment-486555666)_

怎么解决，可以详细一点吗
