### ISSUE TITLE
已知的问题

### ISSUE THREAD

**Issue by hollowtree** [hollowtree/vscode-vue-snippets#3]
* 现在在 `.vue` 文件中，注释快捷键对纯粹的 html / css / js 已经能够区分了，但是如果给 css 加上 lang 属性的话，注释快捷键生成的注释就会发生错误。这个暂时没法改，vs code 插件只能提供两种注释的方式，一种是行注释，一种是块注释，没有针对不同语言提供不同注释方式的选项。

* 现在在写 `.vue` 文件时，css 和 js 还没有智能提示。最新版的 vs code 在写 html 时，已经能够给 css 智能提示了，我看过它的实现方式，挺复杂，而且不能直接移植到 vue 插件中，目前的我写不出类似的给 `.vue` 添加 css 智能提示的插件。至于 js ，现在vs code 也还没实现在html文件中智能提示 js 的功能。

* 总的来说，这个插件现在只是给 `.vue` 文件添加了语法高亮，并且给 `.html` / `.js` / `.vue` 文件添加了相关的vue snippets。

* 如果你发现了bug，或者觉得还需要添加 snippet 的话，或者有其他的建议的话，可以新建issue，或者提交PR。

**Comment by AimLuo** [comment]
看来在html中实现sass高亮有难度啊，我还是用@import来引入不，还好我们现在的项目都是通过这个方式引入的，不然就尴尬 了。

**Comment by plqin-xiaohao** [comment]
注释功能异常: 

![image](https://user-images.githubusercontent.com/41833007/56717940-5e716a80-6770-11e9-8f8e-89a565841f32.png)

使用快捷键  - `ctrl + /` ,  出现异常的注释, 

建议屏蔽 html 中的注释, 使用 vscode 本身的注释功能

**Comment by PLQin** [comment]
vscode 默认的标签扩展功能异常 

当我输入 `div` 后按下 `tab` 键, 之前是会自动扩展为 `<div></div>` , 
但是安装了 `Vue 2 Snippets` 后, 就不会有任何反应了 , 

疑似是屏蔽了默认的功能
