### ISSUE TITLE
Attempting to add snippet within Comment

### ISSUE THREAD

**Issue by rsavage-urquad** [hollowtree/vscode-vue-snippets#34]
While entering a "." (period) within a JavaScript comment (either single line "//" or multi line "/*... */"), a snippet suggestion will be offered - "bundleRenderer.renderToStream".  I just noticed it after VS Code update to 1.45.1.  I don't recall this behavior prior to VS Code update, but I may just not have noticed it.  I disabled "Vue 2 Snippets" to avoid issue.

**Comment by hollowtree** [comment]
thanks~
