### ISSUE TITLE
Can't trigger snippet after triggered "script" snippet!

### ISSUE THREAD

**Issue by zhb124404** [hollowtree/vscode-vue-snippets#35]
# Can't trigger snippet after triggered "script" snippet!

VScode Version:1.45.1
Vue 2 Snippets Version:0.1.11

After I type data to trigger "script" snippet in vue file, I can't trigger any snippet only if I change the cursor position.

I found the  snippet config and changed "$1" to "$0",It works! 
![image](https://user-images.githubusercontent.com/16805041/83094205-bdbc4f80-a0d3-11ea-9977-141384f45ea4.png)

**Comment by hollowtree** [comment]
thanks~
