### ISSUE TITLE
The highlight of vue file is  not work on v0.1.12

### ISSUE THREAD

**Issue by guanbo** [hollowtree/vscode-vue-snippets#36]
## Problem
After upgrade v0.1.12, the highlight of vue file is not work. Under v0.1.11 is fine.

## Environment

version: 1.47.3
commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by hollowtree** [comment]
Try install [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur), it will bring Syntax-highlighting

**Comment by guanbo** [comment]
OK, it' work.
