### ISSUE TITLE
VS Code Search (⇧ ⌘ F) blocked by "vue3snippets.format" command.

### ISSUE THREAD

**Issue by ghost** [hollowtree/vscode-vue-snippets#39]
#### Problem:
`vue3snippets.format` blocks the default VS Code keyboard shortcut for a global search **[⇧ ⌘ F]**.

#### Solution:
Change the shortcut, or describe how to change/disable the command.

Ext. Version: v1.0.26

**Comment by hollowtree** [comment]
[hollowtree.vue-snippets](https://marketplace.visualstudio.com/items?itemName=hollowtree.vue-snippets) don't provide formatter,   maybe you can try to disable other extension one by one, to find specific extension that provide this command.  If you can't find, please list all the extension you installed, thanks.

**Comment by ghost** [comment]
@hollowtree thank you for the notice! Moved to Wscats/vue-snippets https://github.com/Wscats/vue-snippets/issues/14
