### ISSUE TITLE
Styles highlight don't work

### ISSUE THREAD

**Issue by felisio** [hollowtree/vscode-vue-snippets#4]
![captura de tela 2017-01-10 as 08 39 38](https://cloud.githubusercontent.com/assets/647676/21804945/6514e9cc-d710-11e6-8afc-06750377d1b7.png)

**Comment by hollowtree** [comment]
You can add `"files.associations": {  "*.vue": "vue"  }` to your settings.json to make Styles highlight work, but it would let JavaScript and CSS intelliSense not work.

You can try install [vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) to make syntax highlighting and intelliSense work together。

**Comment by felisio** [comment]
Thanks, works !!!

![captura de tela 2017-01-12 as 09 45 17](https://cloud.githubusercontent.com/assets/647676/21890298/ddd8aea6-d8ab-11e6-929d-f031ec5ac526.png)

**Comment by AimLuo** [comment]
vetur 不生效，
禁用vue-snippets，以html方式：
![image](https://cloud.githubusercontent.com/assets/21124342/21976191/9e4c94e2-dc0b-11e6-9d3e-b4b120a1370c.png)
启用vue-snippets，以html方式:
![image](https://cloud.githubusercontent.com/assets/21124342/21976230/d318d636-dc0b-11e6-9d8c-482846357609.png)
启用vue-snippets，以vue方式：
![image](https://cloud.githubusercontent.com/assets/21124342/21976406/99c2b770-dc0c-11e6-8481-b2ab0bdd2f90.png)

**Comment by nicefan** [comment]
我以html方式，关掉了css语法检测，stylus还是不能高亮，不知道readme中的截图是怎么做到的。

**Comment by hollowtree** [comment]
@nicefan 在设置里加上`"files.associations": { "*.vue": "vue" }`。不会这样会使vue文件中的js智能提示失效，你可以安装下 vetur 使语法高亮和js智能提示同时生效。两个插件不会冲突的。Readme有些地方确实写的不是很清楚，这几天会更新的。

**Comment by nicefan** [comment]
装了vetur不设置文件类型，一样不能语法高亮，好郁闷。
