### ISSUE TITLE
vue中的sass语法不支持高亮

### ISSUE THREAD

**Issue by AimLuo** [hollowtree/vscode-vue-snippets#5]
已经按要求去除
"files.associations": {
        "*.vue": "vue"
    }
vue文件按html文档显示
![image](https://cloud.githubusercontent.com/assets/21124342/21975704/0e76be94-dc09-11e6-97d2-57147305c858.png)

**Comment by hollowtree** [comment]
设置里加`"files.associations": { "*.vue": "vue" }`之后可以支持高亮，是因为这样编辑器显示 .vue 文件时采用了对应的高亮文件。不加的话编辑器就以显示 .html 文件的方式来显示 .vue 文件，编辑器显示html是不支持内嵌的scss语法的，所以高亮会出现错误。

vetur那个插件实现了一个Vue语言服务器，目前用这个插件来显示 .vue 比用默认的HTML语言服务器要好。你可以试试加上`"files.associations": { "*.vue": "vue" }`的同时装vetur试试。

你在另一个issue里说的按tab会生成html标签，是因为编辑器将.vue文件当作类似.html的文件处理了。目前VS Code还不支持块作用域snippet，这个暂时还没什么好办法吧。

**Comment by AimLuo** [comment]
我再vetur作者那里留言了，他现在正在解决vue中emmet的问题https://github.com/octref/vetur/issues/14
